"""add_story_tables

Revision ID: 30c05485ac6a
Revises: 0dc6d38eb897
Create Date: 2026-04-12 22:18:09.140505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c05485ac6a'
down_revision: Union[str, None] = '0dc6d38eb897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_user_id'), ['user_id'], unique=False)

    op.create_table('story_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_views_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_views_viewer_id'), ['viewer_id'], unique=False)

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_points_user_id_2', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_points_user_id_2', type_='foreignkey')

    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_views_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_story_views_story_id'))

    op.drop_table('story_views')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_user_id'))

    op.drop_table('stories')
    # ### end Alembic commands ###
