"""add_boost_and_badge_fields

Revision ID: 9249d520c8b1
Revises: 30c05485ac6a
Create Date: 2026-04-13 06:59:32.922299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9249d520c8b1'
down_revision: Union[str, None] = '30c05485ac6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boosted_until', sa.DateTime(timezone=True), nullable=True, comment='피드 상단 노출 만료 시각 (None = 부스트 없음)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge', sa.String(length=30), nullable=True, comment='뱃지 종류 (premium | creator | ...) — None이면 없음'))
        batch_op.add_column(sa.Column('badge_expires_at', sa.DateTime(timezone=True), nullable=True, comment='뱃지 만료 시각'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('badge_expires_at')
        batch_op.drop_column('badge')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('boosted_until')

    # ### end Alembic commands ###
